version: '3.1'
services:
  client:
    container_name: client
    image: client
    build:
      dockerfile: ./client/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server
    links:
      - server
  server:
    container_name: server
    image: server
    build:
      dockerfile: ./server/Dockerfile
    ports:
      - '8000:8000'
    env_file: ./server/src/.env
